registry:
  image: registry:2
  ports:
    - 443:443
  volumes:
    - ./certs:/certs
    - ./data:/var/lib/registry
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_HTTP_ADDR: 0.0.0.0:443
