#!/usr/bin/env bash
set -euo pipefail
. log.sh 

log.begin "[tool]: load ..."

run.fnExists() {
    if type "${1}" &> /dev/null; then
        echo true
    else
        echo false
    fi
}

run.main() {
    log.print "[tool] lib.f exists?: $(run.fnExists lib.f)"
    . lib.sh
    log.print "[tool] lib.f exists?: $(run.fnExists lib.f)"
}


if [[ "$0" == "$BASH_SOURCE" ]]; then
  run.main "$@"
fi

log.begin "[tool]: load done"
